name: minesweeper CI
on:
  push:
    branches:
      - main

jobs:
  mw-build:
    runs-on: ubuntu-latest
    name: minesweeper Push CI
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Installing Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Building
        run: make build
      - name: Linting
        run: |
          golint .
          go vet .
      - name: Testing
        run: make test

          
