name: minesweeper CI
on:
  push:
    branches:
      - main

jobs:
  mw-build:
    runs-on: ubuntu-latest
    name: minesweeper Push CI
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Installing Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Building
        run: make build
      - name: Linting
        run: |
          exec 5>&1
          LINT_OUTPUT="$(make lint | grep -v 'gofmt -d .' | grep -v 'go vet ./...'  | grep -v 'golint ./...' )"
          if [ -n "$LINT_OUTPUT" ]; then
            echo 'Linter ERROR'
            echo "$LINT_OUTPUT"
            exit 1
          else
            echo 'Linter OK'
          fi
      - name: Testing
        run: make test

          
